### PR TITLE
Relay shutdown signal to crawler

### PR DESCRIPTION
**Pull request by qtomlinson**

### CODE REVIEW

**Comment by qtomlinson** [comment]
@MichaelTsengLZ ready for review

**Review by disulliv — APPROVED** [review]

**Review by disulliv — APPROVED** [review]

**Comment by qtomlinson** [comment]
@MichaelTsengLZ ready for review

**Comment by qtomlinson** [comment]
@MichaelTsengLZ Need help to review and merge if it looks good.  :)

**Comment by qtomlinson** [comment]
See https://github.com/clearlydefined/crawler/pull/475/commits/f0e4cfc435dfc040871673ba8ca02ea710999c79 for changes in dockerfile.

**Comment by qtomlinson** [comment]
Nodejs application is set to be PID 1 in the container and can handle termination signals. --init is no longer necessary.

**Pull request closed without merging**
